describe(`App lib`, () => {
    it(`builds request url`, () => {})
    it(`sleep throttling`, () => {})
    it(`prints status`, () => {})
    it(`checks version`, () => {})
    it(`checks version`, () => {})
    it(`converts string version to array of numbers`, () => {})
    it(`gets current application version from the Table Api`, () => {})
    it(`gets current application version from the repository file`, () => {})
})
